#cloud-config
#
# Automating things while initializing physical machines,
# If you want to run manually after you completed installation, copy this file to the server, edit parameters
# and run using below commands
#
# sudo rm -f /var/log/cloud-init*
# sudo cloud-init clean
# sudo cloud-init -f cloud-init.yaml -d modules --mode init
# sudo cloud-init -f cloud-init.yaml -d modules --mode final
#
# cat /var/log/cloud-init* | grep "...."
users:
  - default                                  #creates ubuntu user
  - name: ansible
    groups: [adm, sudo]
    lock_passwd: true                        #if true, login only ssh-key possible
    shell: /bin/bash
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:                     #todo: create your ssh-key, and replace w/ your pub-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnpmIdynltJCwWphGpqotwoQTNQbRVKM1IOA48jb3ZtDFwgaAbvoJBJ5dfMKZ04SkO7Zy3uKlWDP8rOzpwxhPZvwK4+dxOvhoqwfBldIl9u6iGgP7H1HtB7w5Aah9/XISyRb5l+br0s9rnlV4U15VSBRUVnqd1O6L7z/nshWo29mi8IqZPkIUacAj+JAiek3pFoCKBna8KsOYyf8Z9NYBGWmt0Y9Xo7zTpgJrvMkJEy4xMTotDxlnu+LzlGmsLYEDaOD3opQ9Z9jcjM3Et/AeYYtzZZdyGDgJ3h7Pf5jq5Wh9BuDxyX0czGZ4A+mEfUfwUpOJS+kt/8MozG3TVcSHb tansudasli@monster.local
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCVxqHKh51S/USywMWnb3TPDP5R5UBL3+B+73qTb192nCM2rkfmuq5N7Rc7aGSQDEwkLvqgTV9oT2NEillmNLSk+LfKMxF7uJi3xRvRffpPX+uzhuxtSsyv0igIqaEEzOW+qNipk9u4kW3b4akp1fYewQvmdzcgOITiV5ZUyXlXr2TO+jozc9zprRnziIpk3lSV65GQk1GX/B3l6zU5B61OYp0HnZfhhZGWcCv/oaKqHQTWdLgTX30cNw8U0EfQa8EF1YvDCQzfm17ZSynm8/c7gJmgZjDAvP1Zn/hkO6yhxM8yh8ZqIFT8PB3Aq7JSzriROPRhNHgJMVEhOOuTgIXp tansudasli@x1
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDa+8BgTH0S8JwCBBZASD4C74Fp3UH2bpKuCfG4wfjB+ZSG04x9f2Y/AQi9l7e8vq/DgVgqWAv2aeORuIxogVMjlGvMTVELrudY/Icc3ujA1/WffcA/vwc8t6qUz3OTtuwovzA9khA4lCVpgoxsGE5mOTzmCA5qIJcuZUJsrMCN/Tm0nM0dDruXJS3P5BJbs3GYhlVrXQpYQBdjooAcMNbYuyTQ9gsaFtrE3k3tkCDCExc4ZH8juIvepexT4N7sTs5ZPrCfuqe/2cE+TKoEjO8S/OEkwYELhUXxQKoEZkA3FeryTC+RMLLAjqsvxvAjDuTprMIWN0R2kh0ycBS0bBwb ansible@x1

#Below hostname will be replaced w/ regex in bootstrap.yaml
#this part does not update /etc/hosts file.
preserve_hostname: false
prefer_fqdn_over_hostname: false
#fqdn: <fqdn>
hostname: base                               #todo: default hostname value

package_update: true
package_upgrade: true

#runcmd:
#  - echo "=========message========="

#packages:
#  - sshpass                                 # ansible needs, if you use ssh password
#  - openssh-server                          # normally, no need to install here
#  - openjdk-8-jre
#  - pdsh

final_message: "cloud-init is ===finally=== done, after $UPTIME seconds"