# Installs minikube
#
# You can use kvm, docker or none as hypervisor. On virtualbox, docker performs better than kvm (consumes more CPU.

- name: Install minikube
  hosts: k8s
  become: yes
  become_user: ansible
  gather_facts: yes

  vars:
    dummy: ali
    user: minikube
    hypervisor: kvm2                                       #todo: define hypervisor as kvm2|docker|none

  tasks:

    - name: Checks - minikube - OS is Ubuntu
      assert:
        that:
          - "'{{ansible_facts['distribution']}}' == 'Ubuntu'"
        fail_msg: "OS distribution must be Ubuntu"
        success_msg: "OS distribution is ok"

    - name: Checks - minikube - CPU core is gt 1
      assert:
        that:
          - "{{ansible_processor_cores}} > 1"
        fail_msg: "CPU core must be greater than 1. Available = {{ansible_processor_cores}}"
        success_msg: "Available core is {{ansible_processor_cores}}"

    - name: Checks - minikube - RAM is gte 3500mb
      assert:
        that:
          - "{{ansible_memtotal_mb}} >= 3500"
        fail_msg: "Memory must be greater equal than 3500. Available = {{ansible_memtotal_mb}} mb"
        success_msg: "Available memory is {{ansible_memtotal_mb}}"

    - name: Checks - Get / (root) disk size
      shell: df / --output\=avail | tail -1
      register: rootFreeSpace

    - name: Checks - minikube - Disk is gte 50gb
      assert:
        that:
          - "{{rootFreeSpace.stdout | float}} >= 50000000"
        fail_msg: "Disk size must be greater equal than 50gb. Available = {{rootFreeSpace.stdout | float}}kb"
        success_msg: "Available disk is {{rootFreeSpace.stdout | float}} kb"

    - name: User - Create minikube
      user:
        name: minikube
        groups: adm,sudo
        append: yes
        create_home: true
        shell: /bin/bash
      become: yes
      become_user: root

    - include_tasks: tasks/hypervisor_kvm.yaml
      when:
        - hypervisor == 'kvm2'

    - include_tasks: tasks/hypervisor_docker.yaml
      when:
        - hypervisor == 'docker' or hypervisor == 'none'

    - name: kubectl - Get stable version
      command: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
      register: k8sStableVersion

    - name: kubectl - download
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/{{k8sStableVersion.stdout}}/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: a+x
        group: minikube
        owner: minikube
      become: yes
      become_user: root

    - name: minikube - download
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: a+x
        group: minikube
        owner: minikube
      become: yes
      become_user: root


    # at first run, minikube will download approx. 1g data.
    # so, this will take much time !!
#    - name: minikube - start
#      command: minikube start --memory=3000mb --driver={{hypervisor}}
#      become: yes
#      become_user: minikube
#      register: minikubeStatus

    - name: minikube - status
      debug: msg="{{ minikubeStatus }} - "